memoza/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.Register.as_view(), name="signup"),
    path('login/', views.Login.as_view(), name="login"),
    path('logout/', views.Logout.as_view(), name="logout"),
    path('user/<username>', views.UserView.as_view(), name="user"),
]

memoza/memes/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls'), name='posts'),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('', include('posts.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

memoza/posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.Home.as_view(), name="list"),
    path('create/', views.Upload.as_view(), name="create"),
    path('<slug:slug>', views.Meme.as_view(), name="detail"),

]

memoza/accounts/models.py
from django.db import models

# Create your models here.

memoza/posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
import string, random

class Posts(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    score = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    def _get_unique_slug(self):
        slug = slugify(self.title)
        unique_slug = slug
        if unique_slug == '':
            letters = string.ascii_lowercase
            unique_slug = ''.join(random.choice(letters) for i in range(10))
        num = 1
        while Posts.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super().save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Posts'


class Comments(models.Model):
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    post = models.ForeignKey(Posts, on_delete=models.CASCADE)
    content = models.TextField(max_length=512)
    date = models.DateTimeField(auto_now_add=True)
    score = models.IntegerField(default=0)


    def __str__(self):
        return self.content


from django.db import models
from django.contrib.auth.models import User


class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Posts,on_delete=models.CASCADE)
    value = models.IntegerField()
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.user) + ':' + str(self.post) + ':' + str(self.value)

    class Meta:
        unique_together = ("user", "post", "value")

memoza/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

class UserRegister(UserCreationForm):
    email = forms.EmailField(label="Email")

    class Meta:
        model = User
        fields = ("username", "email")

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email and User.objects.filter(email=email).exists():
            raise forms.ValidationError(u'A user with that e-mail already exists.')
        return email

memoza/posts/forms.py
from django import forms
from . import models


class CreatePosts(forms.ModelForm):
    class Meta:
        model = models.Posts
        fields = ['title', 'thumb']

memoza/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from posts.models import Posts
from django.views import View
from .forms import UserRegister


class Register(View):
    def get(self, request):
        form = UserRegister()
        return render(request, 'accounts/signup.html', {'form': form})
    def post(self, request):
        form = UserRegister(request.POST)
        if form.is_valid():
            form.cleaned_data.get("email")
            form.cleaned_data.get("username")
            passwordvalue1 = form.cleaned_data.get("password1")
            passwordvalue2 = form.cleaned_data.get("password2")
            if passwordvalue1 == passwordvalue2:
                user = form.save()
                login(request, user)
                return redirect('posts:list')
            else:
                context = {'form': form, 'error': 'The passwords that you provided don\'t match'}
                return render(request, 'accounts/signup.html', context)

        else:
            context = {'form': form}
            return render(request, 'accounts/signup.html', context)


class Login(View):
    def get(self, request):
        form = AuthenticationForm()
        return render(request, 'accounts/login.html', {'form': form})

    def post(self, request):
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            form.cleaned_data.get("username")
            form.cleaned_data.get("password")
            login(request, user)
            return redirect('posts:list')
        else:
            form = AuthenticationForm()
        return render(request, 'accounts/login.html', {'form': form, 'error': 'The passwords that you provided don\'t match'})




class Logout(View):
    def post(self, request):
        logout(request)
        return redirect('posts:list')


class UserView(View):
    def get(self, request, username):
        user_posts = Posts.objects.filter(author__username=username)
        context = {
            'posts': user_posts.all(),
        }
        return render(request, 'accounts/user.html', context=context)

memoza/posts/views.py
from django.shortcuts import render, redirect
from .models import Posts, Comments
from .forms import CreatePosts
from django.views import View
from django.core.paginator import Paginator
from django.contrib.auth.mixins import LoginRequiredMixin


class Home(View):
    def get(self, request):
        posts = Posts.objects.all()
        paginator = Paginator(posts, 10)
        page = request.GET.get('page')

        posts = paginator.get_page(page)
        context = {'posts': posts}
        return render(request, 'posts/posts_list.html', context)

class Meme(View):
    def get(self, request, slug):
        post = Posts.objects.get(slug=slug)
        context = {
            'post': post,
            'comments': post.comments_set.all(),
        }
        return render(request, 'posts/posts_detail.html', context)

    def post(self, request, slug):
        post = Posts.objects.get(slug=slug)
        Comments.objects.create(author=request.user, post=post, content=request.POST.get('content', ''))
        return redirect('posts:detail', slug)



class Upload(View, LoginRequiredMixin):
    def get(self, request):
        form = CreatePosts()
        return render(request, 'posts/post_create.html', {'form': form})

    def post(self, request):
        form = CreatePosts(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('posts:list')

memoza/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Log in</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}" />
        {% endif %}
        <input type="submit" value="Login" />
    </form>
    <p>Not got an account? <a href="{% url 'accounts:signup' %}">Sign Up</a></p>
{% endblock %}

memoza/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Signup</h1>
    <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

memoza/accounts/templates/accounts/user.html
{% extends 'base_layout.html' %}
{% block content %}
    <h1>Profile Information</h1>
    <div class="Memes">
        {% for i in posts %}
            <div class="Meme">
                <div class="title"><a href="{% url 'posts:detail' i.slug %}">{{ i.title }}</a></div>
                <img src="{{ i.thumb.url }}">
                <div class="date">added on {{i.date}}</div>
                <div class="score">Current score {{ i.score }}</div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

memoza/posts/templates/posts/post_create.html
{% extends 'base_layout.html' %}
{% block content %}
    <div class="create-post">
        <h2>Make an awesome meme!</h2>
        <form class="site-form" action="{% url 'posts:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div>
    <!-- <script src="/static/slugify.js"></script> -->
{% endblock %}

memoza/posts/templates/posts/posts_detail.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="post-container">
        <div class="post-detail">
            <div class="post-detail-title">{{ post.title }}</div>
            <div class="post-detail-image"><img src="{{ post.thumb.url }}"></div>
            <div class="post-detail-author"> Added by <a href="{% url 'accounts:user' post.author.username %}"> {{ post.author.username }} </a></div>
        </div>
        {% if user.is_authenticated %}
        <div class="add-comment">
                 <form class="comment-form" action="{% url 'posts:detail' post.slug %}" method="post">
                    {% csrf_token %}
                    {{ form }}
                     <input type="text" name="content" required>
                     <input type="submit" value="Comment!">
                </form>
        </div>
        {% endif %}
        <div class="comments-title">Comments</div>
        <div class="post-comments">
            {% for comment in comments %}
                <div class="single-comment">
                    <div class="comment-author">{{ comment.author.username }} said:</div>
                    <div class="comment-content">{{ comment.content }}</div>
                    <div class="comment-date">{{ comment.date | timesince }} ago</div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

memoza/posts/templates/posts/posts_list.html
{% extends 'base_layout.html' %}
{% block content %}
    <h1>Memes</h1>
    <div class="Memes">
        {% for i in posts reversed %}
            <div class="Meme">
                <div class="title"><a href="{% url 'posts:detail' i.slug %}">{{ i.title }}</a></div>
                <img src="{{ i.thumb.url }}">
                <div class="author">added by <a href="{% url 'accounts:user' i.author %}">{{ i.author }}</a></div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

<div class="pagination">

  {% if posts.has_previous %}
  <a href="?page=1">First</a>
  <a href="?page={{ posts.previous_page_number }}">Previous</a>
  {% endif %}

  {% for num in posts.paginator.page_range %}

    {% if posts.number == num %}
    <span>{{ num }}</span>
    {% elif num > posts.number|add:'-3' and num < posts.number|add:'3' %}
    <a href="?page={{ num }}">{{ num }}</a>
    {% endif %}

  {% endfor %}

  {% if posts.has_next %}
  <a href="?page={{ posts.next_page_number }}">Next</a>
  <a href="?page={{ posts.paginator.num_pages }}">Last</a>
  {% endif %}

</div>

memoza/templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Memoza</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    </head>
    <body>
        <header class="wrapper">
        <h1><a href="{% url 'posts:list' %}"><img style="height: 200px; width: auto; margin-top: -50px" src="{% static 'logo.png' %}" alt="memes" /></a></h1>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                                {% csrf_token %}
                                <a href="{% url "accounts:user" user.username %}">{{ user.username}}</a> | <button type="submit">Logout</button>
                            </form>
                        </li>
                        <li><a href="{% url 'posts:create' %}" class="highlight">New Meme</a></li>
                    {% else %}
                        <li><a href="{% url 'accounts:login' %}">Login</a></li>
                        <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>